### PR TITLE
Feat/modals

### PR DESCRIPTION
**Pull request by romancitodev**
🎯 This PR pretends to add functionality to the `<Add>` Button showing a modal form to the user to introduce a new patient in the database.

Status: **🚧 WIP**

### CODE REVIEW

**Comment by romancitodev** [comment]
> This is how the modal looks right now: image
> 
> We are investing about the overflow on the footer buttons. image

Fixed!

**Comment by ztamagoru** [comment]
Hotfixes needed:
- [x] Sudden error on DatePicker.tsx not allowing to test personal modal form requirements when 'create' button is clicked. Error image down bellow. DatePicker.tsx works perfectly fine on the patient modal though.

image

**Comment by romancitodev** [comment]
Well, issue detected:
image

The props are loading twice and do not load correctly.

Investating about this and how to fix it.

**Comment by romancitodev** [comment]
Well, Issue detected:

the thing is you actually are setting the controller for one component:
```tsx
<Modal.DatePicker
    placeholder='Fecha de nacimiento'
    max_day={new Date()}
    name='birth'
    control={control}
    error={errors.birth?.message}
/>
```

But in the second one you aren't:
```tsx
<Modal.DatePicker
    name='date_start'
    placeholder='Fecha inicio'
    max_day={ new Date() }
    error={ errors.date_start?.message }
    /* Missing property control */
/>
```

> Hotfixes needed:
> 
> * [x]  Sudden error on DatePicker.tsx not allowing to test personal modal form requirements when 'create' button is clicked. Error image down bellow. DatePicker.tsx works perfectly fine on the patient modal though.
> 
> image

**Comment by ztamagoru** [comment]
- There's a little insignificant bug where closing either the Personal nor the Area modal won't clear the requirement errors, whereas the Patient modal goes do it.

**Comment by ztamagoru** [comment]
Fixed requirement errors' bug when closing form.


> * There's a little insignificant bug where closing either the Personal nor the Area modal won't clear the requirement errors, whereas the Patient modal goes do it.

**Pull request merged**
